package com.cineverse.backend.cinema.integration;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.cineverse.backend.auth.dto.LoginRequest;
import com.cineverse.backend.auth.dto.RegisterRequest;
import com.cineverse.backend.cinema.dto.CreateCinemaRequest;
import com.cineverse.backend.cinema.dto.CreateHallRequest;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import tools.jackson.databind.ObjectMapper;

/**
 * Cinema & Hall Management against a real Postgres (Testcontainers), using
 * the same 401-for-anonymous/403-for-wrong-role split established in
 * MovieAdminFlowIntegrationTest (Phase 2), plus the seat-generation flow.
 */
@SpringBootTest
@AutoConfigureMockMvc
@Testcontainers
class CinemaHallIntegrationTest {

    private static final String SEEDED_CINEMA_ID = "11111111-1111-1111-1111-111111111111";

    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16");

    @DynamicPropertySource
    static void cookieProperties(DynamicPropertyRegistry registry) {
        registry.add("app.security.cookie-secure", () -> "false");
    }

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void publicCanBrowseSeededCinemaHallsAndSeats() throws Exception {
        mockMvc.perform(get("/api/v1/cinemas"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[?(@.name=='CineVerse Downtown')]").exists());

        MvcResult hallsResult = mockMvc.perform(get("/api/v1/cinemas/{id}/halls", SEEDED_CINEMA_ID))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(3))
                .andReturn();

        String hallId = objectMapper.readTree(hallsResult.getResponse().getContentAsString()).get(0).get("id").asText();

        mockMvc.perform(get("/api/v1/halls/{id}/seats", hallId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.hallId").value(hallId))
                .andExpect(jsonPath("$.seats").isArray())
                .andExpect(jsonPath("$.seats[0].rowLabel").exists())
                .andExpect(jsonPath("$.seats[0].columnSpan").exists());
    }

    @Test
    void adminCanCreateCinemaAndHallWithAutoGeneratedSeats() throws Exception {
        String accessToken = loginAsAdmin();

        MvcResult cinemaResult = mockMvc.perform(post("/api/v1/cinemas")
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + accessToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(
                                new CreateCinemaRequest("Test Cinema " + UUID.randomUUID(), "123 Test St"))))
                .andExpect(status().isCreated())
                .andReturn();
        String cinemaId = objectMapper.readTree(cinemaResult.getResponse().getContentAsString()).get("id").asText();

        // 4 rows x 6 columns: rows A-C standard (3x6=18 seats), row D couple (6/2=3 seats) = 21 total.
        MvcResult hallResult = mockMvc.perform(post("/api/v1/cinemas/{id}/halls", cinemaId)
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + accessToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateHallRequest("Hall X", 4, 6))))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.totalRows").value(4))
                .andExpect(jsonPath("$.totalColumns").value(6))
                .andReturn();
        String hallId = objectMapper.readTree(hallResult.getResponse().getContentAsString()).get("id").asText();

        mockMvc.perform(get("/api/v1/cinemas/{id}/halls", cinemaId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(1));

        mockMvc.perform(get("/api/v1/halls/{id}/seats", hallId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.totalRows").value(4))
                .andExpect(jsonPath("$.totalColumns").value(6))
                .andExpect(jsonPath("$.seats.length()").value(21))
                .andExpect(jsonPath("$.seats[?(@.rowLabel=='D')].seatType").value(
                        org.hamcrest.Matchers.everyItem(org.hamcrest.Matchers.is("COUPLE"))))
                .andExpect(jsonPath("$.seats[?(@.rowLabel=='A')].seatType").value(
                        org.hamcrest.Matchers.everyItem(org.hamcrest.Matchers.is("STANDARD"))));
    }

    @Test
    void creatingHallForNonExistentCinemaReturns404() throws Exception {
        String accessToken = loginAsAdmin();

        mockMvc.perform(post("/api/v1/cinemas/{id}/halls", UUID.randomUUID())
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + accessToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateHallRequest("Ghost Hall", 4, 6))))
                .andExpect(status().isNotFound());
    }

    @Test
    void anonymousRequestsToMutateAreRejectedWith401() throws Exception {
        mockMvc.perform(post("/api/v1/cinemas")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateCinemaRequest("Hacked", null))))
                .andExpect(status().isUnauthorized());

        mockMvc.perform(post("/api/v1/cinemas/{id}/halls", SEEDED_CINEMA_ID)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateHallRequest("Hacked Hall", 4, 6))))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void authenticatedCustomerCannotMutateCinemasOrHalls() throws Exception {
        String customerToken = registerAndLoginCustomer();

        mockMvc.perform(post("/api/v1/cinemas")
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + customerToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateCinemaRequest("Hacked", null))))
                .andExpect(status().isForbidden());

        mockMvc.perform(post("/api/v1/cinemas/{id}/halls", SEEDED_CINEMA_ID)
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + customerToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateHallRequest("Hacked Hall", 4, 6))))
                .andExpect(status().isForbidden());
    }

    private String loginAsAdmin() throws Exception {
        MvcResult result = mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(
                                new LoginRequest("admin@cineverse.local", "Admin@12345"))))
                .andExpect(status().isOk())
                .andReturn();
        return objectMapper.readTree(result.getResponse().getContentAsString()).get("accessToken").asText();
    }

    private String registerAndLoginCustomer() throws Exception {
        String email = "customer-" + UUID.randomUUID() + "@cineverse.local";
        String password = "Sup3rSecret!";

        mockMvc.perform(post("/api/v1/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(
                                new RegisterRequest(email, password, "Role Test Customer"))))
                .andExpect(status().isCreated());

        MvcResult result = mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new LoginRequest(email, password))))
                .andExpect(status().isOk())
                .andReturn();
        return objectMapper.readTree(result.getResponse().getContentAsString()).get("accessToken").asText();
    }
}
